--A.
--1)
SELECT * FROM GOALS WHERE BEAUTY BETWEEN  0.1 AND 0.9;

--2)
SELECT DISTINCT(P.PLAYER_ID),TEAM,HOMELAND,MARKET_VALUE FROM PLAYERS AS P, GOALS AS G WHERE TEAM = "FCB" AND P.PLAYER_ID = G.PLAYER_ID;

--3)
SELECT P.PLAYER_ID FROM PLAYERS AS P, GOALS AS G WHERE P.PLAYER_ID = G.PLAYER_ID AND TEAM = "FCB" AND MARKET_VALUE < 8.0 GROUP BY P.PLAYER_ID HAVING COUNT(*) >= 10;

--4)
SELECT TEAM,HOMELAND,COUNT(*) AS NUMBER_OF_GOALS FROM PLAYERS AS P, GOALS AS G WHERE DATE(TIME_STAMP) = "2016-11-23" AND P.PLAYER_ID = G.PLAYER_ID GROUP BY TEAM,HOMELAND;

--5)
SELECT AVG(G.beauty) FROM GOALS as G, PLAYERS as P WHERE (G.player_id = P.player_id) AND (P.team = "PSG");

--B.
--Explanation : In the query at hand, it uses Inner join which returns matching of tables whereas the goal is to return matching and dissimilar data from both tables hence the use of Outer Joins
--Solution : 
SELECT A.PLAYER_ID, B.GOAL_ID FROM PLAYERS AS A LEFT JOIN GOALS B ON A.PLAYER_ID = B.PLAYER_ID ;

--C. 
SELECT COUNT(*), TEAM FROM PLAYERS as P LEFT JOIN GOALS as G on P.PLAYER_ID = G.PLAYER_ID WHERE G.PLAYER_ID IS NULL GROUP BY TEAM;

